apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
type: Opaque
data:
  htpasswd: YWRtaW46JGFwcjEkeFhTa3EzUFUkczNIVC5UbHdMeFFTcGVFd1ZoU1JnMQ==
### ^^^ echo -n 'admin:$apr1$xXSkq3PU$s3HT.TlwLxQSpeEwVhSRg1' | base64 
### https://kubernetes.io/docs/concepts/configuration/secret